# Generated by Django 3.0.8 on 2020-07-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faces', models.IntegerField(blank=True)),
                ('faces_with_masks', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faces', models.IntegerField()),
                ('faces_with_masks', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predicted_image_details', to='api.Image')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='actualimagedetails',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_image_details', to='api.Image'),
        ),
    ]
