# Generated by Django 3.0.8 on 2020-08-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200801_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
