# Generated by Django 3.0.8 on 2020-08-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200813_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'Positive'), ('-1', 'Negative')], default='1', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='api.Image')),
            ],
        ),
    ]
