# Generated by Django 3.0.8 on 2020-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualimagedetails',
            name='faces_with_masks_worn_incorrectly',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictedimagedetails',
            name='faces_with_masks_worn_incorrectly',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
