# Generated by Django 3.0.8 on 2020-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200823_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualimagedetails',
            old_name='faces_with_masks_worn_incorrectly',
            new_name='faces_with_masks_worn_improperly',
        ),
        migrations.RenameField(
            model_name='predictedimagedetails',
            old_name='faces_with_masks_worn_incorrectly',
            new_name='faces_with_masks_worn_improperly',
        ),
    ]
